# Generated by Django 3.1.2 on 2020-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP2Q3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('very bad', 'very bad'), ('bad', 'bad'), ('normal', 'normal'), ('good', 'good'), ('very good', 'very good'), ('showroom', 'showroom')], default=('normal', 'normal'), max_length=9),
        ),
    ]
